### ISSUE TITLE
Recipe instructions are too narrow

### ISSUE THREAD

**Issue by MaxwellBo** [UQComputingSociety/cookbook#6]
The `cuisine` [package documentation](http://mirror.aarnet.edu.au/pub/CTAN/macros/latex/contrib/cuisine/cuisine.pdf) notes a `\RecipeWidths` command (usage: `\RecipeWidths{Total recipe width} {Number of servings width} {Step number width} {Ingredient width} {Quantity width} {Units width}` and `\RecipeWidths{.75\textwidth}{3cm}{0.5cm}{1.75cm}{.75cm}{.75cm}`) can be used to remedy this.

**Comment by TRManderson** [comment]
Feel free to PR and I'll merge :+1:

**Comment by TRManderson** [comment]
It's probably also worth adding parfill/parskip

**Comment by TRManderson** [comment]
Also geometry with 1in margins

**Comment by TRManderson** [comment]
@MaxwellBo Are you happy with the new styles?

**Comment by MaxwellBo** [comment]
Reasonably, might want to keep it open if anyone wants to make it prettier.

**Comment by TRManderson** [comment]
I'll open a separate issue
